# Generated by Django 3.2.13 on 2022-07-22 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userapplication'),
        ('post', '0005_jobpostactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostactivity',
            name='job_application_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userapplication'),
        ),
    ]
